### ISSUE TITLE
CSS- Fonts/Colors/Borders

### ISSUE THREAD

**Issue by oneEyedBunny** [bbigej/Crop-Swap#40]
Ensure all things have font selections, colors borders

**Comment by sandraultreras** [comment]
green = #78AB46 [title, ]
orange = #EBA15A [box background, ]
dark blue = #032559 [borders, shadows, ]
gray = #564E58 [text, ]
off-white = #F2EFEA [backgrounds, ]
FONT = Laura, open sans, HelveticaNeue-Light
BUTTON BACKGROUNDS = orange or off-white
